name: Run Python Script

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 06:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          JWT: ${{ secrets.JWT }}  # JWT token
          API_RESOURCE_WATCH: ${{ secrets.API_RESOURCE_WATCH }}  # API key
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret key
        run: |
          python Download_Data.py
